---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  VITE_API_URL: "http://a351ccb2053904f5d80bfb50b84da3f0-326770733.ap-south-1.elb.amazonaws.com/api"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web
  labels:
    app: node-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
      - name: node-web
        imagePullPolicy: Always
        image: gowrinth225/webapp-2.0:latest
        envFrom:
        - configMapRef:
            name: web-config
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-web
spec:
  type: LoadBalancer
  selector:
    app: node-web
  ports:
  - name: http
    port: 80
    targetPort: 80
